Repository elastic/connectors-ruby, pull requests merged in 2022-09, with the labels that each got.

#287 Follow-up on PR-282
  docs/CONNECTOR_PROTOCOL.md
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: v8.5.0, auto-backport, v8.5.0.0

#288 Fix brittle pipeline param access
  lib/core/connector_settings.rb
  spec/core/connector_settings_spec.rb
Labels: v8.5.0.0

#290 Remove harmful rescue/raise for native_connectors method
  lib/core/elastic_connector_actions.rb
Labels: v8.5.0.0

#285 Use ent-search elasticsearch config if it's on cloud
  lib/app/config.rb
  lib/utility/es_client.rb
  spec/app/config_spec.rb
Labels: v8.5.0, v8.5.0.0

#289 Refactor Core::ConnectorSettings for more consistency
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  spec/core/connector_settings_spec.rb
  spec/core/native_scheduler_spec.rb
Labels: v8.5.0.0

#292 Follow-up on PR-284
  lib/core/elastic_connector_actions.rb
  tests/ftest.rb
Labels: v8.5.0, auto-backport, v8.5.0.0

#291 Connector Schedule does not properly support "Every Week" setting
  lib/utility/cron.rb
  spec/utility/cron_spec.rb
Labels: auto-backport, v8.5.0.0

#293 Add retry_on_failure and request_timeout to ES client
  config/connectors.yml.example
  lib/app/config.rb
  lib/utility/es_client.rb
Labels: v8.5.0, auto-backport, v8.5.0.0

#298 Add system indices retries and change exit code
  lib/app/app.rb
  lib/app/console_app.rb
  lib/app/dispatcher_app.rb
  lib/app/preflight_check.rb
  spec/app/preflight_check_spec.rb
Labels: v8.5.0, auto-backport, v8.5.0.0

#295 Improve and refactor health checks; add healthcheck before a sync
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/core/heartbeat.rb
  lib/core/sync_job_runner.rb
  lib/utility/errors.rb
  spec/connectors/example/connector_spec.rb
  spec/connectors/gitlab/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/core/heartbeat_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: v8.5.0.0

#286 Add Core::Scheduler for Crawler
  connectors_utility.gemspec
  lib/connectors/crawler/scheduler.rb
  lib/connectors_utility.rb
  lib/core/elastic_connector_actions.rb
  lib/utility/constants.rb
  spec/connectors/crawler/crawler_scheduler_spec.rb
Labels: auto-backport, v8.5.0.0

#299 Connector service refactor
  lib/core/connector_settings.rb
  lib/core/native_scheduler.rb
  lib/core/single_scheduler.rb
Labels: auto-backport, v8.5.0.0

#301 Remove params from do_health_check, do_health_check! and is_healthy?
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/mongodb/connector.rb
  spec/connectors/example/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: v8.5.0.0

#297 Make connector service gracefully handle errors
  config/connectors.yml.example
  lib/app/config.rb
  lib/app/dispatcher.rb
  lib/app/dispatcher_app.rb
  lib/core/scheduler.rb
  lib/utility/constants.rb
  spec/app/dispatcher_spec.rb
Labels: v8.5.0, v8.5.0.0

#300 Resolve circular dependency between ElasticConnectorActions and ConnectorSettings
  lib/app/console_app.rb
  lib/app/worker.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/heartbeat.rb
  lib/core/native_scheduler.rb
  lib/core/single_scheduler.rb
  spec/app/worker_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/heartbeat_spec.rb
  spec/core/native_scheduler_spec.rb
  spec/core/single_scheduler_spec.rb
  tests/ftest.rb
Labels: v8.5.0.0

#304 Use Core::ConnectorSettings in Crawler::Scheduler
  lib/connectors/crawler/scheduler.rb
  lib/core/connector_settings.rb
  spec/connectors/crawler/crawler_scheduler_spec.rb
Labels: auto-backport, v8.5.0.0

#308 Add auth handling to MongoDB connector
  Gemfile
  Gemfile.lock
  lib/app/config.rb
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: v8.5.0.0

#309 Change service_type: mongo -> mongodb
  lib/connectors/mongodb/connector.rb
Labels: auto-backport, v8.5.0.0

#312 Fix MongoDB leaking threads if auth is provided
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: auto-backport, v8.5.0.0

#307 Add attachment field to example connector
  lib/connectors/example/connector.rb
  lib/connectors/example/example_attachments/first_attachment.txt
  lib/connectors/example/example_attachments/second_attachment.txt
  lib/connectors/example/example_attachments/third_attachment.txt
  spec/connectors/example/connector_spec.rb
Labels: v8.5.0.0

#316 Add serialization logic to Mongo Connector
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: auto-backport, v8.5.0.0

#294 Add ECS logging
  Gemfile
  Gemfile.lock
  config/connectors.yml.example
  lib/app/config.rb
  lib/utility/logger.rb
Labels: v8.5.0, auto-backport, v8.5.0.0

#315 Display actual first error that happened when applying bulk operations
  lib/utility/es_client.rb
Labels: auto-backport, v8.5.0.0

#313 Base::Connector uses invalid namespace for HealthCheckFailedError
  lib/connectors/base/connector.rb
Labels: auto-backport, v8.5.0.0

#306 Connector service refactor
  config/connectors.yml.example
  lib/app/app.rb
  lib/app/config.rb
  lib/app/dispatcher.rb
  lib/app/worker.rb
  lib/connectors/crawler/scheduler.rb
  lib/core.rb
  lib/core/configuration.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/heartbeat.rb
  lib/core/scheduler.rb
  lib/core/single_scheduler.rb
  lib/core/sync_job_runner.rb
  spec/app/dispatcher_spec.rb
  spec/app/worker_spec.rb
  spec/connectors/crawler/crawler_scheduler_spec.rb
  spec/core/configuration_spec.rb
  spec/core/heartbeat_spec.rb
  spec/core/native_scheduler_spec.rb
  spec/core/scheduler_spec.rb
  spec/core/single_scheduler_spec.rb
  spec/core/sync_job_runner_spec.rb
  tests/connectors.yml
  tests/ftest.rb
Labels: auto-backport, v8.5.0.0

#317 Fix `connectors_service`
  lib/connectors_service.rb
Labels: bug, auto-backport, v8.5.0.0, release-blocker

#319 Use dot notation for App::Config
  connectors_utility.gemspec
  lib/app/config.rb
  lib/app/console_app.rb
  lib/app/preflight_check.rb
  lib/app/version.rb
  lib/core/elastic_connector_actions.rb
  lib/core/output_sink/es_sink.rb
  lib/utility/environment.rb
  lib/utility/es_client.rb
  lib/utility/logger.rb
  spec/utility/es_client_spec.rb
Labels: v8.5.0.0

#320 Remove local_configuration
  README.md
  lib/app/config.rb
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/registry.rb
  lib/utility/errors.rb
  spec/connectors/example/connector_spec.rb
  spec/connectors/gitlab/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: v8.5.0.0

#328 Revert "Use dot notation for App::Config (#319)"
  connectors_utility.gemspec
  lib/app/config.rb
  lib/app/console_app.rb
  lib/app/preflight_check.rb
  lib/app/version.rb
  lib/core/elastic_connector_actions.rb
  lib/core/output_sink/es_sink.rb
  lib/utility/environment.rb
  lib/utility/es_client.rb
  lib/utility/logger.rb
  spec/utility/es_client_spec.rb
Labels: auto-backport, v8.5.0.0

#329 Add required dependencies to the connector_utilities.gemspec file
  Gemfile
  Gemfile.lock
  connectors_utility.gemspec
Labels: auto-backport, v8.5.0.0

#326 run ml inference by default
  lib/core/connector_settings.rb
Labels: auto-backport, v8.5.0.0, v8.6.0.0

#331 Bump main to 8.6
  .backportrc.json
  README.md
  VERSION
Labels: auto-backport, v8.5.0.0

#337 Fix parsing on boolean values in "Direct Connect" MongoDB field
  lib/connectors/mongodb/connector.rb
Labels: backport, v8.5.0, auto-backport, v8.6.0.0

#321 Add more ECS fields
  lib/utility/exception_tracking.rb
  lib/utility/logger.rb
  spec/utility/logger_spec.rb
Labels: auto-backport, v8.5.0.0

#340 [8.5] Add more ECS fields (#321)
  lib/utility/exception_tracking.rb
  lib/utility/logger.rb
  spec/utility/logger_spec.rb
Labels: backport

#327 Move service type check to xxx_registered? methods
  connectors_utility.gemspec
  lib/app/dispatcher.rb
  lib/connectors/crawler/scheduler.rb
  lib/core/scheduler.rb
  spec/app/dispatcher_spec.rb
  spec/core/scheduler_spec.rb
Labels: v8.5.0, auto-backport, v8.5.0.0, v8.6.0.0

#336 Update Pull Request Template to include a manual gem testing step
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.6.0.0

#343 added the dry collection
  .ci/pipelines/connectors.groovy
  Gemfile
  Gemfile.lock
  VERSION
Labels: v8.5.0, auto-backport, v8.6.0.0

#342 [8.5] Move service type check to xxx_registered? methods (#327)
  connectors_utility.gemspec
  lib/app/dispatcher.rb
  lib/connectors/crawler/scheduler.rb
  lib/core/scheduler.rb
  spec/app/dispatcher_spec.rb
  spec/core/scheduler_spec.rb
Labels: backport

#345 [8.5] added the dry collection (#343)
  .ci/pipelines/connectors.groovy
  Gemfile
  Gemfile.lock
  VERSION
Labels: backport

#349 Change log level to reduce noise in the logs
  lib/core/scheduler.rb
Labels: backport, v8.5.0, auto-backport, v8.6.0.1

#344 bump release
  VERSION
Labels: v8.6.0.1

#353 [8.5] bump revision to start next release
  VERSION
Labels: v8.5.0

#354 starting next release
  VERSION
Labels: v8.6.0.0

#338 Fix the remapping confusion of documents id caused by string vs symbol
  lib/connectors/mongodb/connector.rb
  lib/core/scheduler.rb
Labels: backport, v8.5.0, auto-backport, v8.6.0.0
