Repository elastic/connectors-ruby, pull requests merged in 2022-07, with the labels that each got.

#171 Fixing the configurable fields editing
  lib/app/console_app.rb
  lib/core/elastic_connector_actions.rb
Labels: bug, v8.4.0

#184 following up on repo rename
  .backportrc.json
  .ci/jobs/connectors.yml
  config/connectors.yml.example
Labels: v8.4.0

#216 Remove analyzer settings for content index
  config/connectors.yml.example
  lib/app/console_app.rb
  lib/app/worker.rb
  lib/core/elastic_connector_actions.rb
Labels: v8.4.0

#198 Move connector status update to heartbeat
  lib/app/worker.rb
  lib/core.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/heartbeat.rb
  lib/core/sync_job_runner.rb
Labels: v8.4.0

#220 [8.4] Remove analyzer settings for content index (#216)
  config/connectors.yml.example
  lib/app/console_app.rb
  lib/app/worker.rb
  lib/core/elastic_connector_actions.rb
Labels: backport

#221 [8.4] Move connector status update to heartbeat (#198)
  lib/app/worker.rb
  lib/core.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/heartbeat.rb
  lib/core/sync_job_runner.rb
Labels: backport

#218 Fix usage of cron parser for console_app.rb
  lib/app/console_app.rb
Labels: v8.4.0

#225 [8.4] Make connector CONFIGURED if all configurable fields have default values (#217)
  lib/core/heartbeat.rb
Labels: backport

#226 [8.4] Fix usage of cron parser for console_app.rb (#218)
  lib/app/console_app.rb
Labels: backport

#227 Start heartbeat immediately
  lib/app/worker.rb
Labels: backport, v8.4.0
