Repository elastic/connectors-ruby, pull requests merged in 2022-08, with the labels that each got.

#231 add default crawler mappings
  Makefile
  lib/utility/elasticsearch/index/mappings.rb
  spec/utility/elasticsearch/mappings_spec.rb
Labels: backport, v8.4.0, v8.5.0

#233 [8.4] backport mappings changes
  Makefile
  lib/utility/elasticsearch/index/mappings.rb
  spec/utility/elasticsearch/mappings_spec.rb
Labels: backport, v8.4.0

#223 Add analyzer when creating content index
  lib/app/console_app.rb
  lib/core/elastic_connector_actions.rb
Labels: backport, v8.4.0

#237 Rename stub connector to example connector
  lib/connectors/example/connector.rb
  lib/connectors/registry.rb
  spec/utility/es_client_spec.rb
Labels: backport, v8.4.0

#246 [8.4] Disable warnings emited by the Elasticsearch lib (#232)
  config/connectors.yml.example
  lib/app/app.rb
  lib/app/console_app.rb
  lib/app/worker.rb
  lib/utility.rb
  lib/utility/environment.rb
  lib/utility/es_client.rb
  spec/app/worker_spec.rb
Labels: backport

#243 Add 100% spec coverage for Core::SyncJobRunner
  lib/core/sync_job_runner.rb
  lib/utility/es_client.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.5.0.0

#248 GitLab connector does not sync the files and folders properly #2461
  lib/connectors/gitlab/extractor.rb
Labels: backport, auto-backport, v8.5.0.0

#250 [8.4] https://github.com/elastic/enterprise-search-team/issues/2461 - cleaning up leftover code for GitLab files and folders sync (#248)
  lib/connectors/gitlab/extractor.rb
Labels: backport

#251 Fix connector protocol sequence diagram
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.5.0.0

#241 [8.4] Start heartbeat immediately (#227)
  lib/app/worker.rb
Labels: backport

#242 [8.4] Add analyzer when creating content index (#223)
  lib/app/console_app.rb
  lib/core/elastic_connector_actions.rb
Labels: backport

#249 Fixed the Docker environement
  Dockerfile
  Makefile
  README.md
  lib/app/config.rb
  script/run_in_docker.sh
Labels: auto-backport, v8.5.0.0

#256 [8.4] Extract logic for scheduling to a separate class (#235)
  lib/app/worker.rb
  lib/core.rb
  lib/core/connector_settings.rb
  lib/core/scheduler.rb
  lib/core/sync_job_runner.rb
Labels: backport

#252 Add 100% test coverage for Core::ElasticCoreActions
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: v8.5.0.0

#255 [8.4] Functional test (#222)
  Makefile
  lib/connectors_async.rb
  tests/connectors.yml
  tests/docker-compose.yml
  tests/ftest.rb
Labels: backport

#257 [8.4] Clean up stubs/connectors.rb and all usages (#203)
  lib/app/initializers/01_hashie.rb
  lib/app/initializers/02_log_level.rb
  lib/connectors/base/extractor.rb
  lib/stubs/connectors.rb
  lib/stubs/enterprise_search/exception_tracking.rb
  lib/utility.rb
  lib/utility/exception_tracking.rb
  lib/utility/monitor.rb
  spec/connectors/base/extractor_spec.rb
  spec/stubs/connectors_spec.rb
  spec/utility/monitor_spec.rb
Labels: backport

#258 [8.4] Add test coverage for lib/app/worker.rb + modify heartbeat logic for better separation of concerns (#236)
  lib/app/worker.rb
  lib/core/heartbeat.rb
  lib/utility/environment.rb
  spec/app/worker_spec.rb
  spec/core/heartbeat_spec.rb
  spec/utility/es_client_spec.rb
Labels: backport

#244 [8.4] Rename stub connector to example connector (#237)
  lib/connectors/example/connector.rb
  lib/connectors/registry.rb
  spec/utility/es_client_spec.rb
Labels: backport

#260 [8.4] Add 100% coverage for Core::Scheduler (#240)
  spec/core/scheduler_spec.rb
Labels: backport

#261 [8.4] Fix connector protocol sequence diagram (#251)
  docs/CONNECTOR_PROTOCOL.md
Labels: backport

#262 [8.4] Add 100% test coverage for Core::ElasticCoreActions (#252)
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: backport

#253 Delete more files under Connectors::Base that are not used
  lib/connectors/base/authorization.rb
  lib/connectors/base/config.rb
  spec/connectors/base/config_spec.rb
Labels: v8.4.0, auto-backport

#263 [8.4] Delete more files under Connectors::Base that are not used (#253)
  lib/connectors/base/authorization.rb
  lib/connectors/base/config.rb
  spec/connectors/base/config_spec.rb
Labels: backport

#254 Add tests for Core::Output_Sink::* + refactor sinks a bit
  lib/core/output_sink/base_sink.rb
  lib/core/output_sink/console_sink.rb
  lib/core/output_sink/es_sink.rb
  spec/core/output_sink/base_sink_spec.rb
  spec/core/output_sink/combined_sink_spec.rb
  spec/core/output_sink/console_sink_spec.rb
  spec/core/output_sink/es_sink_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples.rb
Labels: v8.4.0, auto-backport

#264 [8.4] Add tests for Core::Output_Sink::* + refactor sinks a bit (#254)
  lib/core/output_sink/base_sink.rb
  lib/core/output_sink/console_sink.rb
  lib/core/output_sink/es_sink.rb
  spec/core/output_sink/base_sink_spec.rb
  spec/core/output_sink/combined_sink_spec.rb
  spec/core/output_sink/console_sink_spec.rb
  spec/core/output_sink/es_sink_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples.rb
Labels: backport

#265 Add tests for mongo connector
  lib/connectors/mongodb/connector.rb
  spec/connectors/gitlab/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/support/shared_examples.rb
Labels: auto-backport, v8.5.0.0

#267 Add example connector test coverage
  spec/connectors/example/connector_spec.rb
Labels: auto-backport, v8.5.0.0

#269 [8.4] Add example connector test coverage (#267)
  spec/connectors/example/connector_spec.rb
Labels: backport

#271 [8.4] Add test coverage for Gitlab Connector (#266)
  lib/connectors/gitlab/connector.rb
  spec/connectors/gitlab/connector_spec.rb
Labels: backport

#185 Connector Service Documentation
  README.md
  config/connectors.yml.example
  docs/SUPPORT.md
Labels: documentation, v8.4.0

#272 [8.4] Connector Service Documentation (#185)
  README.md
  config/connectors.yml.example
  docs/SUPPORT.md
Labels: backport, v8.4.0

#273 Fix missing utility requires
  lib/utility.rb
Labels: v8.4.0, auto-backport, v8.5.0.0

#274 [8.4] Fix missing utility requires (#273)
  lib/utility.rb
Labels: backport

#276 Store service_type for connector in Kibana `.elastic-connectors` index.
  lib/core/heartbeat.rb
  spec/core/heartbeat_spec.rb
Labels: v8.4.0, auto-backport

#277 [8.4] Store service_type for connector in Kibana `.elastic-connectors` index. (#276)
  lib/core/heartbeat.rb
  spec/core/heartbeat_spec.rb
Labels: backport

#278 Make EsClient independent of App::Config
  lib/core/elastic_connector_actions.rb
  lib/core/output_sink/es_sink.rb
  lib/utility/es_client.rb
  spec/utility/es_client_spec.rb
Labels: v8.5.0.0

#279 Add Utility::EsClient to connectors_utility
  connectors_utility.gemspec
  lib/connectors_utility.rb
Labels: v8.5.0.0

#282 [Partial] Connectors recent syncs view #2487 - affected counts on backend
  docs/CONNECTOR_PROTOCOL.md
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: auto-backport, v8.5.0.0

#283 add ingest fields to byoc definition
  docs/CONNECTOR_PROTOCOL.md
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/output_sink/es_sink.rb
  lib/core/sync_job_runner.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/native_scheduler_spec.rb
  spec/core/output_sink/es_sink_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: release_note, auto-backport, v8.5.0.0
