Repository elastic/connectors-ruby, pull requests merged in 2022-05, with the labels that each got.

#93 Remove some logging from the Sinatra app
  lib/app/app.rb
Labels: v8.2.0, v8.3.0

#96 Fix Connectors Require Statements
  lib/app/app.rb
  lib/connectors_sdk/atlassian/custom_client.rb
  lib/connectors_sdk/base/adapter.rb
  lib/connectors_sdk/base/custom_client.rb
  lib/connectors_sdk/base/extractor.rb
  lib/connectors_sdk/confluence/custom_client.rb
  lib/connectors_sdk/office365/config.rb
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_shared/middleware/restrict_hostnames.rb
  spec/connectors_sdk/atlassian/custom_client_spec.rb
  spec/connectors_sdk/base/authorization_spec.rb
  spec/connectors_sdk/base/extractor_spec.rb
  spec/connectors_sdk/base/http_call_wrapper_spec.rb
  spec/connectors_sdk/confluence/adapter_spec.rb
  spec/connectors_sdk/confluence/custom_client_spec.rb
  spec/connectors_sdk/confluence/extractor_spec.rb
  spec/connectors_sdk/confluence_cloud/custom_client_spec.rb
  spec/connectors_sdk/confluence_cloud/extractor_spec.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
  spec/connectors_sdk/office365/extractor_spec.rb
  spec/connectors_sdk/sharepoint/adapter_spec.rb
  spec/connectors_sdk/sharepoint/extractor_spec.rb
  spec/connectors_shared/extraction_utils_spec.rb
  spec/connectors_shared/middleware/restrict_hostnames_spec.rb
  spec/spec_helper.rb
Labels: v8.3.0

#91 Add sites prefix to path
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_sdk/office365/extractor.rb
  lib/connectors_sdk/share_point/adapter.rb
  spec/connectors_sdk/base/http_call_wrapper_spec.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
  spec/connectors_sdk/sharepoint/adapter_spec.rb
  spec/connectors_sdk/sharepoint/extractor_spec.rb
Labels: v8.3.0

#101 Revert :break_after_page flag and all logic around it
  lib/connectors_sdk/confluence/extractor.rb
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_sdk/office365/extractor.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
  spec/connectors_sdk/sharepoint/extractor_spec.rb
Labels: v8.3.0

#105 Release 8.2.1
  VERSION
Labels: v8.2.0

#86 Support custom connectors
  config/connectors.yml.example
  lib/app/app.rb
  lib/connectors_sdk/base/http_call_wrapper.rb
  lib/connectors_sdk/base/registry.rb
  lib/connectors_sdk/confluence_cloud/http_call_wrapper.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  lib/connectors_sdk/stub_connector/http_call_wrapper.rb
  spec/app_spec.rb
Labels: v8.3.0

#98 Add equivalent endpoint
  lib/app/app.rb
  lib/connectors_sdk/base/http_call_wrapper.rb
  lib/connectors_sdk/confluence_cloud/http_call_wrapper.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  spec/app_spec.rb
  spec/connectors_sdk/base/http_call_wrapper_spec.rb
  spec/connectors_sdk/confluence_cloud/http_call_wrapper_spec.rb
  spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Labels: v8.3.0

#104 Renaming HttpCallWrapper => Connector
  lib/connectors_sdk/base/connector.rb
  lib/connectors_sdk/base/registry.rb
  lib/connectors_sdk/confluence_cloud/connector.rb
  lib/connectors_sdk/share_point/connector.rb
  lib/connectors_sdk/stub_connector/connector.rb
  spec/app_spec.rb
  spec/connectors_sdk/base/connector_spec.rb
  spec/connectors_sdk/confluence_cloud/connector_spec.rb
  spec/connectors_sdk/sharepoint/connector_spec.rb
Labels: v8.3.0

#110 Add logic to clean up jobs that are finished or stuck
  lib/connectors_async.rb
  lib/connectors_async/job.rb
  lib/connectors_async/job_store.rb
  lib/connectors_async/job_watcher.rb
  lib/connectors_shared/constants.rb
  spec/connectors_async/job_runner_spec.rb
  spec/connectors_async/job_store_spec.rb
  spec/connectors_async/job_watcher_spec.rb
Labels: v8.3.0
