Repository elastic/connectors-ruby, pull requests merged in 2022-11, with the labels that each got.

#383 update connector protocol
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.6.0.4

#387 Support TLS options for elasticsearch client
  lib/app/config.rb
  lib/utility/es_client.rb
  spec/utility/es_client_spec.rb
Labels: v8.5.0, auto-backport, needs-backport, v8.6.0.4

#396 [8.5] Make better use of memory for Mongo connector when iterating over documents (#362)
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: backport

#397 [8.5] Optimize lifecycle of MongoDB client (#363)
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: backport

#398 [8.5] Add an elasticsearch client bulk patch to reduce memory usage (#364)
  lib/utility/es_client.rb
Labels: backport

#393 Update job status
  lib/connectors/connector_status.rb
  lib/connectors/sync_status.rb
Labels: v8.6.0.4

#399 [8.5] Fix: Inform user about MongoDB connection errors (invalid database/collection) (#368)
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: backport

#400 [8.5] Add Authentication checks to preflight check and connector settings retrieval (#372)
  lib/app/preflight_check.rb
  lib/core/native_scheduler.rb
  lib/core/scheduler.rb
  lib/core/single_scheduler.rb
  lib/utility/errors.rb
  spec/app/preflight_check_spec.rb
  spec/core/native_scheduler_spec.rb
  spec/core/single_scheduler_spec.rb
Labels: backport

#401 [8.5] Allow strings and symbols for configurable fields in connectors (#380)
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/core/configuration.rb
  spec/core/configuration_spec.rb
Labels: backport

#402 [8.5] Termination of connectors shows error (#381)
  lib/connectors/example/connector.rb
  lib/core/sync_job_runner.rb
  spec/core/sync_job_runner_spec.rb
Labels: backport

#385 Add filtering capability (by an advanced config) to MongoDB connector
  lib/connectors/base/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/registry.rb
  lib/core/connector_settings.rb
  lib/core/sync_job_runner.rb
  lib/utility.rb
  lib/utility/common.rb
  lib/utility/errors.rb
  spec/connectors/base/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/sync_job_runner_spec.rb
  spec/utility/common_spec.rb
Labels: auto-backport, v8.6.0.4

#405 Ensure connector instantiations line up
  connectors_service.gemspec
  connectors_utility.gemspec
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/registry.rb
  lib/core/sync_job_runner.rb
Labels: auto-backport, v8.6.0.4

#404 Drop OutputSink::CombinedSink
  lib/core/output_sink.rb
  lib/core/output_sink/combined_sink.rb
  spec/core/output_sink/combined_sink_spec.rb
Labels: v8.6.0.0, v8.6.0.4

#403 Persist filtering in job records
  lib/core/elastic_connector_actions.rb
  lib/core/sync_job_runner.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#406 Add unit test, when a sync thread is stopped
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#407 Use key specified in connectors mapping for advanced filter config
  lib/connectors/base/connector.rb
  spec/connectors/base/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/core/connector_settings_spec.rb
Labels: auto-backport, v8.6.0.4

#386 Add metadata to connector protocol and job index mapping
  docs/CONNECTOR_PROTOCOL.md
  lib/core/elastic_connector_actions.rb
Labels: auto-backport, v8.6.0.0, v8.6.0.4

#390 Report metadata during job execution
  lib/connectors/base/connector.rb
  lib/core/elastic_connector_actions.rb
  lib/core/output_sink/es_sink.rb
  lib/core/sync_job_runner.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/sync_job_runner_spec.rb
  spec/support/shared_examples.rb
Labels: auto-backport, v8.6.0.4

#410 [Mongo] add "simple" pre-processing filtering logic
  lib/connectors/base/connector.rb
  lib/connectors/base/simple_rules_parser.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/mongodb/mongo_rules_parser.rb
  lib/core/elastic_connector_actions.rb
  lib/core/sync_job_runner.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#389 Implement dynamic elasticsearch data flushing
  lib/connectors/base/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/core/ingestion.rb
  lib/core/ingestion/console_sink.rb
  lib/core/ingestion/es_sink.rb
  lib/core/ingestion/ingester.rb
  lib/core/output_sink/base_sink.rb
  lib/core/output_sink/console_sink.rb
  lib/core/output_sink/es_sink.rb
  lib/core/sync_job_runner.rb
  lib/utility.rb
  lib/utility/bulk_queue.rb
  spec/core/ingestion/console_sink_spec.rb
  spec/core/ingestion/es_sink_spec.rb
  spec/core/ingestion/ingester_spec.rb
  spec/core/output_sink/base_sink_spec.rb
  spec/core/output_sink/console_sink_spec.rb
  spec/core/output_sink/es_sink_spec.rb
  spec/core/sync_job_runner_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples.rb
  spec/utility/bulk_queue_spec.rb
Labels: auto-backport, v8.6.0.4

#415 Make tests more consistent
  spec/connectors/base/adapter_spec.rb
  spec/connectors/base/connector_spec.rb
  spec/connectors/base/custom_client_spec.rb
  spec/connectors/example/connector_spec.rb
  spec/connectors/gitlab/adapter_spec.rb
  spec/connectors/gitlab/connector_spec.rb
  spec/connectors/gitlab/extractor_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
  spec/connectors/registry_spec.rb
  spec/core/configuration_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/heartbeat_spec.rb
  spec/core/ingestion/console_sink_spec.rb
  spec/core/ingestion/es_sink_spec.rb
  spec/core/sync_job_runner_spec.rb
  spec/utility/bulk_queue_spec.rb
  spec/utility/common_spec.rb
  spec/utility/exception_tracking_spec.rb
  spec/utility/logger_spec.rb
Labels: auto-backport, v8.6.0.4

#414 Ensure, that the is_shutting_down check is also executed, if an exception was raised
  lib/core/scheduler.rb
  spec/core/scheduler_spec.rb
Labels: auto-backport, v8.6.0.4

#408 Add filtering rule features to ruby connectors
  docs/CONNECTOR_PROTOCOL.md
  lib/connectors/base/connector.rb
  lib/core/configuration.rb
  lib/core/elastic_connector_actions.rb
  lib/utility/constants.rb
  spec/core/configuration_spec.rb
Labels: v8.6.0.4

#417 Refactor some test methods to adhere to spec best practices
  spec/connectors/base/connector_spec.rb
  spec/connectors/gitlab/connector_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/filtering/validation_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#422 Use utility function for filter extraction.
  lib/connectors/mongodb/connector.rb
  lib/utility/filtering.rb
Labels: auto-backport, v8.6.0.4

#419 Delete Core::Ingestion::ConsoleSink
  lib/core/ingestion.rb
  lib/core/ingestion/console_sink.rb
  spec/core/ingestion/console_sink_spec.rb
Labels: v8.6.0.4

#421 Ignore large documents when ingesting the data
  lib/core/ingestion/ingester.rb
  spec/core/ingestion/ingester_spec.rb
Labels: v8.6.0.4

#416 Add Job Entity
  lib/core.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  spec/core/connector_job_spec.rb
Labels: auto-backport, v8.6.0.4

#424 Update connector service to adopt the index mapping change
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: v8.6.0.4

#426 Refactor sinks to be more simple and robust
  lib/core/ingestion.rb
  lib/core/ingestion/es_sink.rb
  lib/core/ingestion/ingester.rb
  lib/core/sync_job_runner.rb
  spec/core/ingestion/es_sink_spec.rb
  spec/core/ingestion/ingester_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: v8.6.0.4

#429 Return nil instead of raising error if the connector/job is not found
  lib/connectors/sync_status.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/single_scheduler.rb
  spec/core/connector_job_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/single_scheduler_spec.rb
Labels: auto-backport, v8.6.0.4

#427 Add sync jobs producer and consumer
  .gitignore
  lib/app/app.rb
  lib/app/dispatcher.rb
  lib/core.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/jobs/consumer.rb
  lib/core/jobs/producer.rb
  lib/core/sync_job_runner.rb
  spec/app/dispatcher_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/sync_job_runner_spec.rb
  spec/spec_helper.rb
Labels: v8.6.0.4

#435 Add error monitor logic
  connectors_utility.gemspec
  lib/connectors/base/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/tolerable_error_helper.rb
  lib/utility.rb
  lib/utility/error_monitor.rb
  lib/utility/errors.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/connectors/tolerable_error_helper_spec.rb
  spec/utility/error_monitor_spec.rb
Labels: release_note, v8.6.0.4

#434 Make it possible to specify maximum size/volume of ingestion queue
  config/connectors.yml.example
  docs/CONFIG.md
  lib/app/config.rb
  lib/app/dispatcher.rb
  lib/core/ingestion/es_sink.rb
  lib/core/jobs/consumer.rb
  lib/core/sync_job_runner.rb
  lib/utility/bulk_queue.rb
  lib/utility/constants.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#438 Bump main to 8.7
  VERSION
Labels: v8.7.0

#440 Add more tests for fields constraints and unify two method calls
  lib/connectors/base/advanced_snippet_against_schema_validator.rb
  spec/connectors/base/advanced_snippet_against_schema_validator_spec.rb
Labels: auto-backport, v8.7.0.0

#439 Mark "find.filter" in the advanced snippet (MongoDB) as optional
  lib/connectors/base/advanced_snippet_against_schema_validator.rb
  lib/connectors/mongodb/mongo_advanced_snippet_schema.rb
  spec/connectors/base/advanced_snippet_against_schema_validator_spec.rb
  spec/connectors/mongodb/mongo_advanced_snippet_against_schema_validator_spec.rb
Labels: auto-backport, v8.7.0.0

#441 Add tests to registry_spec
  spec/connectors/registry_spec.rb
Labels: auto-backport, v8.7.0.0

#432 Start sync when scheduling is enabled and properly configured and there's no sync before
  lib/core/scheduler.rb
  spec/core/scheduler_spec.rb
Labels: auto-backport, v8.6.0

#443 gemspecs: drop dependency on app/config
  connectors_service.gemspec
  connectors_utility.gemspec
Labels: v8.7.0.0

#444 Fix backportrc for 8.6
  .backportrc.json
Labels: auto-backport, v8.7.0.0

#411 Validate job during job execution
  connectors_utility.gemspec
  lib/connectors/base/connector.rb
  lib/connectors/example/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/registry.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/filtering/post_process_engine.rb
  lib/core/sync_job_runner.rb
  lib/utility/bulk_queue.rb
  spec/connectors/base/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/filtering/post_process_engine_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0

#446 [8.6] Start sync when scheduling is enabled and properly configured and there's no sync before (#432)
  lib/core/scheduler.rb
  spec/core/scheduler_spec.rb
Labels: backport

#428 Add Job cleanup task
  config/connectors.yml.example
  docs/CONFIG.md
  lib/app/config.rb
  lib/app/dispatcher.rb
  lib/core.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/job_cleanup.rb
  spec/app/dispatcher_spec.rb
  spec/core/job_cleanup_spec.rb
Labels: auto-backport, v8.6.0

#447 Update RELEASING.md
  docs/RELEASING.md
Labels: auto-backport, v8.7.0.0

#455 Extending RELEASING.md to add instructions about logging into rubygems.
  docs/RELEASING.md
Labels: backport, auto-backport, v8.6.0.0, 8.7, v8.6.0, v8.7.0.0

#458 Fix: Implementation for MongoDB simple rules pre-processing for 'starts_with', 'ends_with' and 'contains' missing
  lib/connectors/mongodb/mongo_rules_parser.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
Labels: auto-backport, v8.7.0.0

#460 Include connector_job
  lib/connectors_utility.rb
Labels: auto-backport, v8.6.0, v8.7.0.0

#456 Replace Consumer.loop by TimerTask
  lib/core/jobs/consumer.rb
  lib/core/jobs/producer.rb
  spec/app/dispatcher_spec.rb
  spec/core/jobs/consumer_spec.rb
  spec/core/jobs/producer_spec.rb
Labels: auto-backport, v8.6.0, v8.7.0.0

#462 Update connector status after job completes
  lib/core/connector_settings.rb
  spec/core/connector_settings_spec.rb
Labels: auto-backport, v8.6.0

#463 Bump version
  VERSION
Labels: v8.5.0

#445 Fix the extraction of the dependencies in the gemspec
  connectors_service.gemspec
Labels: auto-backport, v8.7.0.0

#450 Use connector data in job during execution
  connectors_utility.gemspec
  docs/CONNECTOR_PROTOCOL.md
  lib/app/dispatcher.rb
  lib/connectors/base/connector.rb
  lib/connectors/gitlab/connector.rb
  lib/connectors/job_trigger_method.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors_utility.rb
  lib/core/connector_job.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/scheduler.rb
  lib/core/sync_job_runner.rb
  spec/connectors/base/connector_spec.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/core/connector_settings_spec.rb
  spec/core/scheduler_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0

#471 Update connector protocol to specify filtering rules as array
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.7.0, v8.6.0, v8.7.0.0

#442 Fix a problem with error monitor and max_error_ratio being incorrectly handled
  lib/utility/error_monitor.rb
  spec/utility/error_monitor_spec.rb
Labels: auto-backport, v8.6.0

#476 Fix: snake_case MongoDB filtering
  lib/connectors/base/connector.rb
  lib/connectors/mongodb/connector.rb
  lib/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer.rb
  lib/core/filtering/transform/filter_transformer.rb
  lib/core/filtering/transform/filter_transformer_facade.rb
  lib/core/filtering/transform/transformation_target.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/connectors/mongodb/mongo_filter_snake_case_transformer_spec.rb
  spec/core/filtering/transform/filter_transformer_facade_spec.rb
  spec/core/filtering/transform/filter_transformer_spec.rb
Labels: auto-backport, v8.6.0.0, v8.6.0, v8.7.0.0

#473 Fix: MongoDB aggregation pipelines not working
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: auto-backport, v8.6.0.0, v8.6.0, v8.7.0.0

#483 Specifying the backport version and giving directions
  .gitignore
  docs/DEVELOPING.md
  package.json
  yarn.lock
Labels: auto-backport, v8.7.0.0

#484 [8.6] Fix: Add nil guard for advanced snippet during transformation (#479)
  lib/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer.rb
  spec/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer_spec.rb
Labels: backport, v8.6.0

#486 [8.6] Fix: Implementation for MongoDB simple rules pre-processing for 'starts_with', 'ends_with' and 'contains' missing (#458)
  lib/connectors/mongodb/mongo_rules_parser.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
Labels: backport, v8.6.0

#487 Update version to latest unreleased SNAPSHOT
  VERSION
Labels: v8.6.0

#488 Fix: Exclude DEFAULT simple rule from match all regex check
  lib/core/filtering/simple_rules/validation/simple_rules_schema.rb
  spec/core/filtering/simple_rule/single_rule_against_schema_validator_spec.rb
  spec/support/shared_examples/filtering.rb
Labels: auto-backport, v8.6.0.0, v8.6.0, v8.7.0.0

#480 bug: pre-procesing simple rules turns int into str #3348
  lib/connectors/mongodb/mongo_rules_parser.rb
  lib/core/filtering/simple_rules/simple_rule.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
Labels: backport, auto-backport, v8.6.0, v8.7.0.0, v8.6.1

#491 Fix: Advanced Snippet should be accessible with Strings and Symbols
  lib/connectors/base/connector.rb
  spec/connectors/base/connector_spec.rb
Labels: auto-backport, v8.6.0.0, v8.6.0, v8.7.0.0
