Repository elastic/connectors-ruby, pull requests merged in 2022-12, with the labels that each got.

#493 Add more fatal exceptions
  lib/connectors/tolerable_error_helper.rb
Labels: auto-backport, v8.6.0, v8.6.1

#495 Fix: [MongoDB Connector] Missing aggregation pipeline crashes sync job
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: auto-backport, v8.7.0, v8.6.0

#500 Disabling this workflow
  .github/workflows/add-to-repo.yml
Labels: auto-backport, v8.7.0.0

#502 Make it possible to send headers to Elasticsearch clients from config
  lib/app/config.rb
  lib/utility/es_client.rb
  spec/app/config_spec.rb
  spec/utility/es_client_spec.rb
Labels: v8.5.0, auto-backport, v8.6.0, v8.7.0.0

#505 Relax activesupport dependency requirement
  connectors_utility.gemspec
Labels: auto-backport, v8.7.0.0

#508 Update CONNECTOR_PROTOCOL.md
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.7.0.0
