Repository elastic/connectors-ruby, pull requests merged in 2022-04, with the labels that each got.

#67 Updated version to 8.3
  VERSION
  config/connectors.yml.example
Labels: v8.3.0

#68 Index permissions in document
  Gemfile.lock
  lib/app/app.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Labels: v8.2.0

#62 Test connectors with ent search - Part 2
  .gitignore
  Makefile
  README.md
  config/connectors.yml
  lib/app/app.rb
  lib/connectors_app/config.rb
Labels: v8.2.0

#70 Return cursors at the end of extraction
  lib/app/app.rb
  lib/connectors_sdk/base/extractor.rb
  lib/connectors_sdk/office365/config.rb
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_sdk/office365/extractor.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
  spec/connectors_sdk/sharepoint/extractor_spec.rb
Labels: v8.2.0

#69 Paginate over the contents of a single SharePoint Online folder node
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_sdk/office365/extractor.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
Labels: v8.2.0

#79 small updates
  .backportrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  docs/INTERNAL.md
Labels: v8.3.0

#77 [8.2][Backport] Paginate over the contents of a single SharePoint Online folder node (#69)
  lib/connectors_sdk/office365/custom_client.rb
  lib/connectors_sdk/office365/extractor.rb
  spec/connectors_sdk/office365/custom_client_spec.rb
Labels: v8.2.0

#76 [8.2] backport release command
  .bundler-version
  .gitignore
  Makefile
  README.md
  VERSION
  config/connectors.yml.example
  docs/RELEASING.md
  script/version.sh
Labels: v8.2.0

#78 [8.2] backport windows build
  .ci/pipelines/connectors.groovy
  Gemfile
  Gemfile.lock
  README.md
  make.bat
  win32/getmsys2.vbs
  win32/install.bat
Labels: v8.2.0

#82 Clarify rbenv requirement
  README.md
  docs/DEVELOPING.md
Labels: v8.3.0

#83 Stop caching the instance of HttpCallWrapper, which caused it to behave like a singleton class
  lib/app/app.rb
  lib/connectors_sdk/base/registry.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  spec/app_spec.rb
  spec/connectors_sdk/base/registry_spec.rb
  spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Labels: v8.2.0, v8.3.0

#84 [8.2] Stop caching the instance of HttpCallWrapper, which caused it to behave like a singleton class (#83)
  lib/app/app.rb
  lib/connectors_sdk/base/registry.rb
  lib/connectors_sdk/share_point/http_call_wrapper.rb
  spec/app_spec.rb
  spec/connectors_sdk/base/registry_spec.rb
  spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Labels: backport

#74 Fixes to make the external connector work with rack-based managed hosting like Heroku
  .bundler-version
  Gemfile
  Gemfile.lock
  Makefile
  Procfile
  README.md
  docs/DEVELOPING.md
  lib/app/app.rb
Labels: v8.3.0
