Repository elastic/connectors-ruby, pull requests merged in 2022-10, with the labels that each got.

#358 Fix last sync status FAILED to follow the protocol
  lib/connectors/sync_status.rb
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: v8.5.0, auto-backport, v8.6.0.3

#365 Update DEVELOPING.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.6.0.3

#366 Fix example connector
  lib/connectors/example/attachments/first_attachment.txt
  lib/connectors/example/attachments/second_attachment.txt
  lib/connectors/example/attachments/third_attachment.txt
  lib/connectors/example/connector.rb
  spec/connectors/example/connector_spec.rb
Labels: auto-backport, v8.6.0.3

#368 Fix: Inform user about MongoDB connection errors (invalid database/collection)
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: auto-backport, v8.6.0.3

#371 Update pull request template to include a link to instruction how to build and test gems
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.6.0.3

#363 Optimize lifecycle of MongoDB client
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: release_note, auto-backport, v8.6.0.3

#372 Add Authentication checks to preflight check and connector settings retrieval
  lib/app/preflight_check.rb
  lib/core/native_scheduler.rb
  lib/core/scheduler.rb
  lib/core/single_scheduler.rb
  lib/utility/errors.rb
  spec/app/preflight_check_spec.rb
  spec/core/native_scheduler_spec.rb
  spec/core/single_scheduler_spec.rb
Labels: auto-backport, v8.6.0.3

#367 Connector service documentation
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/CONFIG.md
  docs/CONNECTOR_PROTOCOL.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/INTERNAL.md
  docs/RELEASING.md
  docs/SECURITY.md
  docs/SUPPORT.md
  docs/TERMINOLOGY.md
Labels: v8.5.0, auto-backport, v8.6.0.3

#376 [8.5] Connector service documentation (#367)
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/CONFIG.md
  docs/CONNECTOR_PROTOCOL.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/INTERNAL.md
  docs/RELEASING.md
  docs/SECURITY.md
  docs/SUPPORT.md
  docs/TERMINOLOGY.md
Labels: backport

#360 use strings everywhere
  lib/connectors/mongodb/connector.rb
  lib/core/sync_job_runner.rb
Labels: auto-backport, v8.6.0.3, needs-backport

#356 starting 8604
  VERSION
Labels: auto-backport, v8.6.0.3

#357 Multiple concurrent syncs hanging
  lib/app/dispatcher.rb
  lib/core/connector_settings.rb
  lib/core/elastic_connector_actions.rb
  lib/core/scheduler.rb
  lib/core/sync_job_runner.rb
  spec/app/dispatcher_spec.rb
  spec/core/elastic_connector_actions_spec.rb
  spec/core/scheduler_spec.rb
Labels: bug, backport, v8.5.0, auto-backport, v8.6.0.0, v8.6.0.3

#364 Add an elasticsearch client bulk patch to reduce memory usage
  lib/utility/es_client.rb
Labels: auto-backport, v8.6.0.3, needs-backport

#381 Termination of connectors shows error
  lib/connectors/example/connector.rb
  lib/core/sync_job_runner.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.6.0.4

#362 Make better use of memory for Mongo connector when iterating over documents
  lib/connectors/mongodb/connector.rb
  spec/connectors/mongodb/connector_spec.rb
Labels: release_note, auto-backport, v8.6.0.3, needs-backport

#384 Revert "Add an elasticsearch client bulk patch to reduce memory usage"
  lib/utility/es_client.rb
Labels: auto-backport, v8.6.0.4
