Repository elastic/connectors-ruby, pull requests merged in 2022-06, with the labels that each got.

#121 Update/correct example `repository` value
  config/connectors.yml.example
Labels: v8.4.0

#112 Add Configuration File Validation
  Gemfile
  Gemfile.lock
  lib/app/app.rb
  lib/connectors_app/config.rb
  lib/connectors_async/job_runner.rb
Labels: v8.3.0

#118 Enable api keys for confluence cloud
  Makefile
  connectors_sdk.gemspec
  connectors_stubs.gemspec
  lib/connectors_sdk/atlassian/custom_client.rb
Labels: v8.4.0, release_note

#122 Bumping the version
  VERSION
Labels: v8.2.3

#89 Blog code: Gitlab connector
  lib/connectors_async/job.rb
  lib/connectors_sdk/base/registry.rb
  lib/connectors_sdk/gitlab/adapter.rb
  lib/connectors_sdk/gitlab/config.rb
  lib/connectors_sdk/gitlab/connector.rb
  lib/connectors_sdk/gitlab/custom_client.rb
  lib/connectors_sdk/gitlab/extractor.rb
  spec/connectors_sdk/gitlab/adapter_spec.rb
  spec/connectors_sdk/gitlab/connector_spec.rb
  spec/connectors_sdk/gitlab/extractor_spec.rb
  spec/fixtures/gitlab/external_user.json
  spec/fixtures/gitlab/external_users.json
  spec/fixtures/gitlab/project.json
  spec/fixtures/gitlab/project_members.json
  spec/fixtures/gitlab/projects_list.json
  spec/fixtures/gitlab/simple_project.json
  spec/fixtures/gitlab/user.json
Labels: v8.3.0

#123 Minor copyedit to `readme`: add missing word to heading
  README.md
Labels: documentation
