Repository elastic/connectors-ruby, pull requests merged in 2023-08, with the labels that each got.

#563 Bump rack and activesupport
  Gemfile
  Gemfile.lock
Labels: auto-backport, v8.10.0.0, v8.10.0.1, v8.10.0

#571 Add Primary Buildkite Pipeline Migration
  .buildkite/pipeline.yml
  .buildkite/scripts/run_ci_step.sh
  .buildkite/scripts/run_command.sh
Labels: auto-backport, v8.11.0.0

#572 [CI] [Buildkite] Decomission Jenkins Pipeline Jobs
  .ci/jobs/connectors.yml
  .ci/jobs/nightly-qa.yml
Labels: auto-backport, v8.11.0, v8.11.0.0
