Repository elastic/connectors-ruby, pull requests merged in 2023-01, with the labels that each got.

#509 Add custom_scheduling to connector protocol
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.7.0.0

#510 [Filtering] Remove Basic Rules Integration Filtering from MongoDB connector
  lib/connectors/mongodb/connector.rb
  lib/connectors/mongodb/mongo_rules_parser.rb
  spec/connectors/mongodb/connector_spec.rb
  spec/connectors/mongodb/mongo_rules_parser_spec.rb
Labels: auto-backport, v8.7.0.0

#512 [Filtering] Allow custom error messages for custom type matching functions
  lib/core/filtering/hash_against_schema_validator.rb
  spec/core/filtering/hash_against_schema_validator_spec.rb
Labels: auto-backport, v8.7.0.0

#515 Fix makefile for arm64
  Gemfile.lock
  Makefile
Labels: auto-backport, v8.7.0, v8.7.0.0, v8.6.1

#517 Update elasticsearcy client to 8.6.0
  Gemfile
  Gemfile.lock
Labels: v8.7.0, v8.7.0.0

#511 [Filtering] Respect filtering feature flags
  lib/core/connector_settings.rb
  lib/core/scheduler.rb
  lib/core/sync_job_runner.rb
  spec/core/connector_settings_spec.rb
  spec/core/scheduler_spec.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.7.0.0

#518 Add more pull request checklist items
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.7.0, v8.6.0, v8.7.0.0

#520 Bump rack to 2.2.6.2
  Gemfile.lock
Labels: auto-backport, v8.7.0, v8.7.0.0, v8.6.1

#521 Bump tzinfo-data
  Gemfile.lock
Labels: auto-backport, v8.7.0, v8.7.0.0, v8.6.1

#525 Add method for updating custom_scheduling last_synced
  lib/core/elastic_connector_actions.rb
  spec/core/elastic_connector_actions_spec.rb
Labels: v8.7.0, v8.7.0.0
