Repository elastic/connectors-ruby, pull requests merged in 2023-02, with the labels that each got.

#528 Don't delete content indices used by existing connectors
  lib/app/dispatcher.rb
  lib/core/connector_job.rb
  lib/core/elastic_connector_actions.rb
  lib/core/job_cleanup.rb
  lib/core/jobs/consumer.rb
  spec/core/job_cleanup_spec.rb
Labels: auto-backport, v8.7.0, v8.7.0.0

#529 Reset last_sync_error when claiming a job
  lib/core/elastic_connector_actions.rb
  lib/core/sync_job_runner.rb
  spec/core/sync_job_runner_spec.rb
Labels: auto-backport, v8.7.0, v8.7.0.0

#526 Add id to connector indices + dynamic: false
  docs/CONNECTOR_PROTOCOL.md
  lib/core/elastic_connector_actions.rb
Labels: auto-backport, v8.7.0.0

#530 Implement nested features
  docs/CONNECTOR_PROTOCOL.md
  lib/connectors/base/connector.rb
  lib/core/configuration.rb
  lib/core/connector_settings.rb
  lib/utility/constants.rb
  spec/core/configuration_spec.rb
  spec/core/connector_settings_spec.rb
Labels: auto-backport, 8.7, v8.7.0.0

#531 Fix the bug that connector starts sync immediately when scheduled
  lib/connectors/crawler/scheduler.rb
  lib/core/scheduler.rb
  spec/connectors/crawler/crawler_scheduler_spec.rb
  spec/core/scheduler_spec.rb
Labels: auto-backport, v8.7.0, v8.7.0.0

#534 [8.7] Fix the bug that connector starts sync immediately when scheduled (#531)
  lib/connectors/crawler/scheduler.rb
  lib/core/scheduler.rb
  spec/connectors/crawler/crawler_scheduler_spec.rb
  spec/core/scheduler_spec.rb
Labels: backport

#532 Bump main to 8.8
  .backportrc.json
  VERSION
Labels: auto-backport, v8.7.0.0

#536 [Docs] Connector protocol was moved to connectors-python
  README.md
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.8.0.0

#535 Rename stuck jobs to idle jobs
  lib/core/connector_job.rb
  lib/core/job_cleanup.rb
  spec/core/job_cleanup_spec.rb
Labels: auto-backport, v8.7.0, v8.8.0.0

#537 [8.7] Rename stuck jobs to idle jobs (#535)
  lib/core/connector_job.rb
  lib/core/job_cleanup.rb
  spec/core/job_cleanup_spec.rb
Labels: backport

#538 Update .backportrc.json
  .backportrc.json
Labels: v8.8.0.0

#540 Allow arbitrary levels of postfix versions in .backportrc
  .backportrc.json
Labels: auto-backport, v8.8.0.0

#541 remove prompt=consent in favor of prompt=select_account
  lib/connectors_sdk/share_point/authorization.rb
Labels: v8.3.0, release_note
